interpreter: /bin/sh

startup:
  - mbar
  - awww-daemon
  - ghkd -b -c ~/.config/ghkd/config.yaml
  - wlsunset -t 4000 -T 4500
  - ~/.local/bin/wall.sh
  - swayosd-server
  - swayidle -w timeout 300 'kitty --class screensaver --start-as fullscreen -o background_opacity=1 bash "$HOME/.local/bin/screensaver.sh"'
