interpreter: /bin/sh

startup:
  - quickshell
  - veilad
  - awww-daemon
  - ghkd -b -c ~/.config/ghkd/config.yaml
  - wlsunset -t 4000 -T 4500
  - wl-paste --watch cliphist store
  - ~/.local/bin/wall.sh
  - swayosd-server
  - swayidle -w timeout 300 'veila lock' timeout 600 '[ "$(cat /proc/1/comm)" = systemd ] && ctl=systemctl || ctl=loginctl; $ctl suspend'
  - poweralertd -S
