import QtQuick
import QtQuick.Layouts
import Quickshell
import "../../Services"
import "../../Widgets"

StatusPill {
    required property var bar
    required property var popup
    id: wifiPill
    // Type-driven, from active CONNECTIONS (never route ifaces — a VPN's
    // default route is a tunnel device whose autogenerated name leaked here
    // on both the wifi and wired branches before).
    icon: Net.netSsid !== "" ? Theme.wifiIcon(Net.netSignal)
        : Net.netEthName !== "" ? "󰈀"
        : Net.netIface !== "" ? "󰛳"
        : "󰖪"
    iconColor: Net.netSsid !== "" || Net.netEthName !== "" ? Theme.green
             : Net.netIface !== "" ? Theme.fgDim : Theme.red
    value: Net.netSsid !== "" ? Net.netSsid
         : Net.netEthName !== "" ? Net.netEthName
         : Net.netIface !== "" ? "connected"
         : "off"
    maxValueWidth: 150
    tooltip: "network"
    onClicked: {
        bar.togglePopupAt(popup, wifiPill);
        if (popup.visible && Net.wifiEnabled) Net.scanWifi();
    }
}
