pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: displayCtl

    // ================= night light (wlsunset) =================
    // Flag file = truth; enforcer reconciles. Key insight: wlsunset is a
    // SCHEDULER — "-t 4000 -T 6500" shows 6500K (no tint) in daytime, so a
    // toggle backed by it looks dead at noon. ON therefore runs a forced-warm
    // instance (-t 4000 -T 4050: warm at any hour); schedule-mode instances
    // (e.g. an exec-once autostart) are replaced while the flag is on and
    // killed while it is off. The autostart line can stay in mango config.
    property bool nightLight: false

    Process {
        id: nlEnforce
        command: ["sh", "-c", `FLAG="$HOME/.config/mango/nightlight-on"
forced=0; other=0
for p in $(pgrep -x wlsunset 2>/dev/null); do
  [ "$(cut -d\  -f3 "/proc/$p/stat" 2>/dev/null)" = Z ] && continue
  if grep -aq -- "-T.4050" "/proc/$p/cmdline" 2>/dev/null; then forced=1; else other=1; fi
done
if [ -f "$FLAG" ]; then
  # ON must mean visibly warm NOW: schedule-mode instances (autostart) show
  # daytime 6500K, so replace them with our forced-warm one
  if [ $forced -eq 0 ]; then
    [ $other -eq 1 ] && { pkill -x wlsunset; sleep 0.4; }
    setsid -f sh -c 'exec wlsunset -t 4000 -T 4050 >>/tmp/wlsunset.log 2>&1'
  fi
else
  pkill -x wlsunset 2>/dev/null
fi`]
        running: true
    }

    Process {   // startup: UI state = flag
        command: ["sh", "-c", '[ -f "$HOME/.config/mango/nightlight-on" ]']
        running: true
        onExited: code => displayCtl.nightLight = (code === 0)
    }

    function toggleNightLight() {
        nightLight = !nightLight;
        Quickshell.execDetached(["sh", "-c", nightLight
            ? 'touch "$HOME/.config/mango/nightlight-on"'
            : 'rm -f "$HOME/.config/mango/nightlight-on"']);
        nlKick.restart();
    }
    Timer { id: nlKick; interval: 250; onTriggered: nlEnforce.running = true }

    // ================= brightness (brightnessctl) =================
    property int brightness: -1
    Process {
        id: briGet
        command: ["sh", "-c", "brightnessctl -m 2>/dev/null | cut -d, -f4 | tr -d %"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: brightness = text.trim() === "" ? -1 : parseInt(text.trim())
        }
    }
    property int briPending: -1
    Process {
        id: briSet
        command: ["sh", "-c", "brightnessctl set " + displayCtl.briPending + "% >/dev/null 2>&1"]
        onExited: briGet.running = true
    }
    function adjustFromWheel(delta) {
        if (brightness >= 0) setBrightness(brightness + (delta > 0 ? 5 : -5));
    }
    function setBrightness(pct) {
        briPending = Math.max(1, Math.min(100, Math.round(pct)));
        // optimistic: move the bound property NOW so sliders track the drag
        // continuously; the post-apply poll confirms (or corrects) it.
        brightness = briPending;
        briApply.restart();
    }
    Timer { id: briApply; interval: 120; onTriggered: briSet.running = true }

    // ================= display persistence =================
    // wlr-randr changes die with the compositor; every apply rewrites
    // ~/.config/mango/monitors.sh, replayed by exec-once at startup.
    property var dispPersist: ({})

    function _writeDispState() {
        let script = "#!/bin/sh\n# generated by quickshell — display settings\nsleep 1\n";
        for (const name in dispPersist) {
            const e = dispPersist[name];
            script += "wlr-randr --output '" + name + "'";
            if (e.on === false) { script += " --off\n"; continue; }
            if (e.on === true)  script += " --on";
            if (e.mode)         script += " --mode " + e.mode;
            if (e.scale !== undefined)     script += " --scale " + e.scale;
            if (e.transform !== undefined) script += " --transform " + e.transform;
            if (e.pos !== undefined)       script += " --pos " + e.pos;
            script += "\n";
        }
        Quickshell.execDetached(["sh", "-c",
            'mkdir -p "$HOME/.config/mango" && printf %s "$1" > "$HOME/.config/mango/monitors.json" && printf %s "$2" > "$HOME/.config/mango/monitors.sh" && chmod +x "$HOME/.config/mango/monitors.sh"',
            "_", JSON.stringify(dispPersist), script]);
    }

    function persistDisplay(outName, patch) {
        const next = Object.assign({}, dispPersist);
        next[outName] = Object.assign({}, next[outName] ?? {}, patch);
        dispPersist = next;
        _writeDispState();
    }

    function applyPersisted() {
        for (const name in dispPersist) {
            const e = dispPersist[name];
            const cmd = ["wlr-randr", "--output", name];
            if (e.on === false) { Quickshell.execDetached(cmd.concat(["--off"])); continue; }
            if (e.on === true)  cmd.push("--on");
            if (e.mode)         cmd.push("--mode", e.mode);
            if (e.scale !== undefined)     cmd.push("--scale", String(e.scale));
            if (e.transform !== undefined) cmd.push("--transform", String(e.transform));
            if (e.pos !== undefined)       cmd.push("--pos", String(e.pos));
            if (cmd.length > 3) Quickshell.execDetached(cmd);
        }
    }

    // load saved state at startup, then self-apply — no exec-once line required
    Process {
        id: dispLoad
        command: ["sh", "-c", 'cat "$HOME/.config/mango/monitors.json" 2>/dev/null || echo "{}"']
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                try { dispPersist = JSON.parse(text.trim() || "{}"); }
                catch (e) { dispPersist = {}; }
                dispApplyDelay.start();
            }
        }
    }
    Timer { id: dispApplyDelay; interval: 1500; onTriggered: applyPersisted() }


    Timer {
        interval: 10000; running: true; repeat: true
        onTriggered: { nlEnforce.running = true; briGet.running = true }
    }
}
